[project]
name = "pr004"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "helainev", email = "polmast2@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "accelerate>=1.15.0",
    "bitsandbytes>=0.50.2",
    "jupyter>=1.1.1",
    "streamlit>=1.63.0",
    "torch>=2.14.0",
    "transformers>=5.17.0",
]

[project.scripts]
pr004 = "pr004:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
